<?php

namespace ContainerC31GWDB;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator__T9_6gCService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator..t9.6gC' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator..t9.6gC'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\Auth\\LoginController::index' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\Auth\\RegistrationController::index' => ['privates', '.service_locator.Mhqdd2r', 'get_ServiceLocator_Mhqdd2rService', true],
            'App\\Controller\\Companies\\CreateCompanyController::index' => ['privates', '.service_locator.YgYapZ6', 'get_ServiceLocator_YgYapZ6Service', true],
            'App\\Controller\\Companies\\MyCompanyController::index' => ['privates', '.service_locator.YgYapZ6', 'get_ServiceLocator_YgYapZ6Service', true],
            'App\\Controller\\Offers\\Company\\MyOffersController::index' => ['privates', '.service_locator.YgYapZ6', 'get_ServiceLocator_YgYapZ6Service', true],
            'App\\Controller\\Offers\\CreateOffersController::index' => ['privates', '.service_locator.YgYapZ6', 'get_ServiceLocator_YgYapZ6Service', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\Auth\\LoginController:index' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\Auth\\RegistrationController:index' => ['privates', '.service_locator.Mhqdd2r', 'get_ServiceLocator_Mhqdd2rService', true],
            'App\\Controller\\Companies\\CreateCompanyController:index' => ['privates', '.service_locator.YgYapZ6', 'get_ServiceLocator_YgYapZ6Service', true],
            'App\\Controller\\Companies\\MyCompanyController:index' => ['privates', '.service_locator.YgYapZ6', 'get_ServiceLocator_YgYapZ6Service', true],
            'App\\Controller\\Offers\\Company\\MyOffersController:index' => ['privates', '.service_locator.YgYapZ6', 'get_ServiceLocator_YgYapZ6Service', true],
            'App\\Controller\\Offers\\CreateOffersController:index' => ['privates', '.service_locator.YgYapZ6', 'get_ServiceLocator_YgYapZ6Service', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\Auth\\LoginController::index' => '?',
            'App\\Controller\\Auth\\RegistrationController::index' => '?',
            'App\\Controller\\Companies\\CreateCompanyController::index' => '?',
            'App\\Controller\\Companies\\MyCompanyController::index' => '?',
            'App\\Controller\\Offers\\Company\\MyOffersController::index' => '?',
            'App\\Controller\\Offers\\CreateOffersController::index' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\Auth\\LoginController:index' => '?',
            'App\\Controller\\Auth\\RegistrationController:index' => '?',
            'App\\Controller\\Companies\\CreateCompanyController:index' => '?',
            'App\\Controller\\Companies\\MyCompanyController:index' => '?',
            'App\\Controller\\Offers\\Company\\MyOffersController:index' => '?',
            'App\\Controller\\Offers\\CreateOffersController:index' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
