<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRIcsHxw\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRIcsHxw/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRIcsHxw.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRIcsHxw\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRIcsHxw\App_KernelDevDebugContainer([
    'container.build_hash' => 'RIcsHxw',
    'container.build_id' => '2b9f234e',
    'container.build_time' => 1679915642,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRIcsHxw');
