<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXXt0YyX\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXXt0YyX/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXXt0YyX.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXXt0YyX\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXXt0YyX\App_KernelDevDebugContainer([
    'container.build_hash' => 'XXt0YyX',
    'container.build_id' => '5aae9fd2',
    'container.build_time' => 1680030223,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXXt0YyX');
