<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6ntxCbe\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6ntxCbe/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container6ntxCbe.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container6ntxCbe\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container6ntxCbe\App_KernelDevDebugContainer([
    'container.build_hash' => '6ntxCbe',
    'container.build_id' => '0a3058e1',
    'container.build_time' => 1679900604,
], __DIR__.\DIRECTORY_SEPARATOR.'Container6ntxCbe');
