<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], [], []],
    '_profiler_xdebug' => [[], ['_controller' => 'web_profiler.controller.profiler::xdebugAction'], [], [['text', '/_profiler/xdebug']], [], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\Auth\\LoginController::index'], [], [['text', '/login']], [], [], []],
    'app_logout' => [[], ['_controller' => 'App\\Controller\\Auth\\LoginController::logout'], [], [['text', '/logout']], [], [], []],
    'app_registration' => [[], ['_controller' => 'App\\Controller\\Auth\\RegistrationController::index'], [], [['text', '/registration']], [], [], []],
    'app_companies' => [[], ['_controller' => 'App\\Controller\\Companies\\CompanyController::index'], [], [['text', '/companies']], [], [], []],
    'app__create_company' => [[], ['_controller' => 'App\\Controller\\Companies\\CreateCompanyController::index'], [], [['text', '/my-company/create']], [], [], []],
    'app_my_company' => [[], ['_controller' => 'App\\Controller\\Companies\\MyCompanyController::index'], [], [['text', '/my-company']], [], [], []],
    'app_my_company_edit' => [[], ['_controller' => 'App\\Controller\\Companies\\MyCompanyController::edit'], [], [['text', '/my-company/edit']], [], [], []],
    'homepage' => [[], ['_controller' => 'App\\Controller\\HomePageController::index'], [], [['text', '/']], [], [], []],
    'app_my_offers' => [[], ['_controller' => 'App\\Controller\\Offers\\Company\\MyOffersController::index'], [], [['text', '/my-offers']], [], [], []],
    'app_offers_create_offers' => [[], ['_controller' => 'App\\Controller\\Offers\\CreateOffersController::index'], [], [['text', '/my-offers/create']], [], [], []],
    'app_offers' => [[], ['_controller' => 'App\\Controller\\Offers\\OffersController::index'], [], [['text', '/offers']], [], [], []],
    'app_individual_offer' => [['id'], ['_controller' => 'App\\Controller\\Offers\\OffersController::offer'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/offers']], [], [], []],
    'app_permission_denied' => [[], ['_controller' => 'App\\Controller\\PermissionDeniedController::index'], [], [['text', '/permission/denied']], [], [], []],
];
